word_list = [
    "UDEMY", "LAMBORGHINI", "FERRARI", "MCLAREN", "RANGE",
    "COMPUTER", "VACATION", "GIRLFRIEND", "PYTHON", "PROGRAMMING",
    "KEYBOARD", "MONITOR", "INTERNET", "WEBSITE", "DATABASE",
    "SOFTWARE", "HARDWARE", "ALGORITHM", "FUNCTION", "VARIABLE",
    "ELEPHANT", "GIRAFFE", "PENGUIN", "DOLPHIN", "TIGER",
    "LION", "MONKEY", "ZEBRA", "TURTLE", "BUTTERFLY",
    "PIZZA", "BURGER", "CHOCOLATE", "PANCAKE", "STRAWBERRY",
    "PINEAPPLE", "WATERMELON", "SANDWICH", "SPAGHETTI", "POPCORN",
    "AIRPLANE", "BICYCLE", "MOTORCYCLE", "HELICOPTER", "TRAIN",
    "ROCKET", "SUBMARINE", "SAILBOAT", "TRACTOR", "SCOOTER",
    "MOUNTAIN", "FOREST", "DESERT", "OCEAN", "ISLAND",
    "VOLCANO", "WATERFALL", "RAINBOW", "THUNDER", "SNOWFLAKE",
    "FOOTBALL", "BASKETBALL", "TENNIS", "SWIMMING", "CYCLING",
    "GUITAR", "PIANO", "DRUMS", "VIOLIN", "TRUMPET",
    "ASTRONAUT", "PLANET", "GALAXY", "SATELLITE", "UNIVERSE"
]